title:              J. T. Caldeira
email:              jt.brazaocaldeira@gmail.com
description:        
author:             J. T. Caldeira
url:                "https://JTCaldeira.github.io"

# Social Profiles
github_username:    JTCaldeira
instagram_username:  
linkedin_username:  joão-tomás-caldeira

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
