title:              J. T. Caldeira
email:              jt.brazaocaldeira@gmail.com
description:        
author:             J. T. Caldeira
url:                "https://JTCaldeira.github.io"

# Social Profiles
github_username:    JTCaldeira
instagram_username:  
linkedin_username:  joão-tomás-caldeira

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


collections:
  learning:
    output: true
    permalink: /:collection/:title
    sort_by: lesson_number


defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "learning"
    values:
      layout: "chapter"
  -
    scope:
      path: "_learning/prerequisites"
    values:
      tag: "Prerequisites"
  -
    scope:
      path: "_learning/deep-learning"
    values:
      tag: "Deep Learning"
  -
    scope:
      path: "_learning/machine-learning"
    values:
      tag: "Machine Learning"
  -
    scope:
      path: "_learning/math"
    values:
      tag: "Math"